---
- name: Ensure locale is available
  locale_gen: name=en_US.UTF-8

- name: Install PostgreSQL
  apt:
    pkg:
      - postgresql
      - postgresql-contrib
      # - postgresql-server-dev-all
      - python3-psycopg2
      # - python-psycopg2
    state: latest

- name: Start and enable postgres
  service: name=postgresql enabled=yes state=started

- name: Create database
  become: true
  become_user: postgres
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present
  notify:
  - postgresql restart

# - name: Add user postgres to root group
#   shell:
#     cmd: usermod -a -G root

- name: Create user
  become: yes
  become_user: postgres 
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv="CONNECT/products:ALL"
                   encrypted=yes
