---
- hosts: project_server
  gather_facts: no
  become: true

  pre_tasks:
    - name: check host
      shell: | 
        hostname
      register: out
    - name: Show host
      debug:
        msg: "{{ out.stdout }}"

    - name: test shell
      shell: |
        cat /etc/os-release
      register: out
    - name: Show host
      debug:
        msg: "{{ out.stdout }}"




#   roles:
#     - nginx
#     - postgresql
#     - django
#     - gunicorn