---
- name: update os
  shell:
    cmd: apt update -y
    
- name: Install base needed apt-packages
  apt:
    name: "{{ apt_http_packages }}"
    state: latest
    update_cache: yes

- name: Add foldef rog jenkins connect
  file: 
    path: /home/jenkins 
    state: directory