- name: gunicorn_start
  service: 
    name: gunicorn 
    state: started

- name: gunicorn_enable
  service: 
    name: gunicorn 
    state: enabled

- name: Reload_systemd_units
  command: systemctl daemon-reload