---
- name: Clone git repo
  git:
    repo: '{{ git_url }}'
    dest: '{{ project_path }}'
    version: '{{ web_release }}'

# - name: Make migrations
#   shell: "{{project_name_path}}/env/bin/python3 {{ project_name_path }}/{{ project_name }}/manage.py makemigrations"

# - name: Migrate database
#   django_manage: app_path={{ project_name_path }}/{{ project_name }}
#                         command=migrate
#                         virtualenv={{project_name_path}}/env

# - name: Get all static files
#   django_manage: app_path={{ project_name_path }}/{{ project_name }}
#                         command=collectstatic
#                         virtualenv={{project_name_path}}/env 